# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 552adefaede400f8d657d3cb9ee34c8568aa3402c6536e954acc91703cccfa452597aa9d22e094cce4625f18786a0471f8331be84cee9f160d3f875f418b758c

test:
  secret_key_base: db4bf870e7e0384d1dfc711d5b78f17618c2bf85316160a11d47d11dc2bc148fabc2b168566b77ad8ee488e41142a0e3f431ba21cf7d15c7a0115b5a0e8d6ec4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
